parameters:
#    fb_hack_beer.example.class: FbHack\BeerBundle\Example

services:
#    fb_hack_beer.example:
#        class: %fb_hack_beer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
